### ISSUE TITLE
请问如何设置 google analysis ？

### ISSUE THREAD

**Issue by zhiyue** [mayneyao/gatsby-starter-gine-blog#5]
我看到 https://gine.me/posts/54fc4aaa38434d92afddf5d4b75b76b0#8fdd7880-aa9b-4404-9bf6-53a8d7d1fddb 里面提到已经集成 google analysis 。请问如何设置呢？

**Comment by mayneyao** [comment]
@zhiyue  你好，文章写的很早，后来博客重构了。ga 没有加入基础功能中，但是配置起来很简单。参见 dev-mayne（master 是你部署时的默认分支，包含基础功能）分支下的 gatsby-config.js 
https://github.com/mayneyao/gatsby-starter-gine-blog/blob/e4ba165aa62d335ea89acc619ac628abe763b5be/gatsby-config.js#L20-L26

这些可选的高级功能，自己修改配置，安装插件即可。具体的使用方法，查看插件文档。
https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by zhiyue** [comment]
好的。谢谢
